permalink: pretty

theme: jekyll_patternbot

patternbot:
  title: "MK Design"
  description: |
    Welcome to MK Design.

  colors:
    background: "--color-primary"
    accent: "--color-accent"
    sidebar: "--color-primary-dark"

  rationales:
    colors.primary: |
      White serves as the default site colour for the light-mode backgrounds, which is interchangeable with its dark-mode counterpart. These solid colours provide high-contrast bases which support extremely readable text content.
    colors.secondary: |
      These colours serve to form the default text colours, and are the inverse of the primary colour schemes found above.
    colors.accent: |
      These colors serve different functions:


      Accent is used to draw attention to the most critical components on site pages, including important calls-to-action, headers, and navigation components.


      Hover is used to indicate what selection on a page the mouse is hovering on, or which is tab-selected by keyboard.


      Error is used to visually differentiate sections of a site that require user attention, including form errors.
    typefaces.primary: |
      The primary font for this site needed to be professional, clean, and reflective of standard practices in the digital sector. Thus, Helvetica was selected as the default font, due to its readability, its pervasiveness in technology, and its efficiency in terms of loading times.

collections:
  projects:
    output: true

defaults:
  - scope:
      path: _projects
    values:
      layout: project