title: "Navigations"
description: |
  Navigations function to help users visit various sections of the website, as well as link to related external content.

patterns:
  header:
    title: "Header"
    description: |
      This is the primary navigation bar of the site, and allows users to navigate between the main site pages.
  footer:
    title: "Footer"
    description: |
      This is the footer navigation bar of the site, and sits (surprisingly) in the footer. It links to relevant SNS content for the MK Design brand.
  secondary:
    title: "Secondary Navigation"
    description: |
      This is the secondary navigation bar of the site, and is located in the project detail view. It navigates between project pages.